#!/bin/sh

make_resolv_conf() {
  local first=1
  echo nameserver 127.0.0.1 > /etc/resolv.conf
  echo >> /etc/resolv.conf
  for n in $new_domain_name_servers ; do
    if [ "$first" = "1" -a "$n" != "127.0.0.1" ] ; then
      echo "#proxy-nameserver $n" >> /etc/resolv.conf
      echo DNSADDR $n | socat UNIX-CONNECT:/var/run/dnsbackend.sock STDIO > /dev/null 2>&1 || return $?
      first=0
    else
      if [ "$n" != "127.0.0.1" ] ; then
        echo nameserver $n >> /etc/resolv.conf
      fi
    fi
  done
}
